environment:
  nodejs_version: "9"
cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
test_script:
  - .\bin\run --version
  - .\bin\run --help
  - yarn test
after_test:
  - .\node_modules\.bin\nyc report --reporter text-lcov > coverage.lcov
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

build: off

