[build]
  # This will be run the site build
  command = "npm run site:build"
  # This is the directory is publishing to netlify's CDN
  publish = "site/dist"

  [build.environment]
    NODE_VERSION = "12"

#####################
#  Redirect Rules   #
#####################
[[redirects]]
  # Telemetry link
  from = "/telemetry/track"
  to = "https://cli-telemetry.netlify.engineering/.netlify/functions/track"
  status = 302
  force = false
[[redirects]]
   # Telemetry link
  from = "/telemetry/identify"
  to = "https://cli-telemetry.netlify.engineering/.netlify/functions/identify"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/mac"
  to = "https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-darwin-amd64-0.4.0.tar.gz"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/linux"
  to = "https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/windows"
  to = "https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-windows-amd64-0.4.0.zip"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/source-zip"
  to = "https://github.com/netlify/netlifyctl/archive/v0.4.0.zip"
  status = 302
  force = false
[[redirects]]
  # Old CLI download links.
  from = "/download/latest/source-tar"
  to = "https://github.com/netlify/netlifyctl/archive/v0.4.0.tar.gz"
  status = 302
  force = false
