name: Package size

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  package-size:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          check-latest: true
      - name: Install dependencies
        run: npm ci --no-audit && npm prune --production
      - name: Get size
        run: du -sk node_modules | cut -f1 > .delta.packageSize && echo "kb (Package size)" >> .delta.packageSize
      - name: Run Delta
        uses: netlify/delta-action@v2
        with:
          title: 'ðŸ“Š Benchmark results'
          token: ${{ secrets.GITHUB_TOKEN }}
