---
name: Post benchmarks
on:
  workflow_run:
    workflows: [Calculate benchmarks]
    types:
      - completed

jobs:
  post-package-size:
    runs-on: ubuntu-latest
    steps:
      # This posts the status to the PR/commit
      - uses: haya14busa/action-workflow_run-status@v1

      - name: Download deltas
        uses: dawidd6/action-download-artifact@v11
        with:
          # This is the workflow that triggered this run
          workflow: ${{ github.event.workflow.id }}
          workflow_conclusion: success
          name: delta-action-deltas
          if_no_artifact_found: ignore
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check File Existence
        id: check-file-existence
        uses: thebinaryfelix/check-file-existence-action@1.0.1
        with:
          files: '.delta.*'

      - name: Get PR number
        if: github.event.workflow_run.event == 'pull_request' && steps.check-file-existence.outputs.exists == 'true'
        id: pr_number
        run: echo "pr_number=$(cat pr_number)" >> $GITHUB_OUTPUT

      - name: Post deltas to GitHub
        if: steps.check-file-existence.outputs.exists == 'true'
        uses: netlify/delta-action@v4
        with:
          title: 'ðŸ“Š Benchmark results'
          style: 'text'
          pr_number: ${{ steps.pr_number.outputs.pr_number }}
