name: Calculate package size

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  package-size:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci --no-audit --foreground-scripts && npm prune --production
      - name: Get size
        run: du -sk node_modules | cut -f1 > .delta.packageSize && echo "kb (Package size)" >> .delta.packageSize
      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > ./pr_number
      - name: Upload deltas
        uses: actions/upload-artifact@v3
        with:
          name: delta-action-deltas
          retention-days: 7
          path: |
            .delta.*
            pr_number
