name: Dependency License Scanning

on:
  push:
    branches:
      - main
      - fossa

defaults:
  run:
    shell: bash

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fossa init
        run: |-
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
          fossa init
      - name: Set env
        run: echo "line_number=$(grep -n "project" .fossa.yml | cut -f1 -d:)" >> $GITHUB_ENV
      - name: Configuration
        run: |-
          sed -i "${line_number}s|.*|  project: git@github.com:${GITHUB_REPOSITORY}.git|" .fossa.yml
          cat .fossa.yml
      - name: Set env for unused_go/hello-world
        run: |-
          echo "unused_go_line_number=$(grep -m 1 -n "unused_go/hello-world" .fossa.yml | cut -f1 -d:)" >> $GITHUB_ENV
          echo "unused_go_last_line_number=$(grep -n "unused_go/hello-world" .fossa.yml | tail -1 | cut -f1 -d:)" >> $GITHUB_ENV
      - name: Remove unused_go/hello-world module
        run: sed -i "${unused_go_line_number},${unused_go_last_line_number}d" .fossa.yml
      - name: Upload dependencies
        run: fossa analyze --debug
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
