---
name: prerelease
on:
  push:
    branches:
      # releases/<tag>/<version>
      - releases/*/*
jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Install core dependencies
        run: npm ci --no-audit

      - name: Build project
        run: npm run build

      - name: Extract tag and version
        id: extract
        run: |-
          ref=${{ github.ref }}
          branch=${ref:11}
          tag_version=${branch:9}
          tag=${tag_version%/*}
          version=${tag_version##*/}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Log versions
        run: |-
          echo tag=${{ steps.extract.outputs.tag }}
          echo version=${{ steps.extract.outputs.version }}

      - name: Configure Git user
        run: |
          git config --global user.name "Netlify"
          git config --global user.email "82042599+token-generator-app[bot]@users.noreply.github.com"

      - name: Run npm version
        run: npm version ${{ steps.extract.outputs.version }}-${{ steps.extract.outputs.tag }} --allow-same-version

      - name: Push changes
        run: git push --follow-tags

      - name: Run npm publish
        run: npm publish --tag=${{ steps.extract.outputs.tag }} --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
